env:
  global:
    - CC_TEST_REPORTER_ID=8ccae69cdbc0c5e8cceaf9d81d8a31f54949043e7be8574404ff86d7b8257072
language: java
jdk: openjdk8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter format-coverage target/site/jacoco-aggregate/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage